trigger:
  tags:
    exclude:
      - '*'

jobs:
  - job: test
    displayName: Run tests

    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'

      - task: Npm@1
        displayName: Install dependencies
        inputs:
          command: ci

      - task: Npm@1
        displayName: Build
        inputs:
          command: custom
          customCommand: run-script build

      - task: Npm@1
        displayName: Browser tests
        inputs:
          command: custom
          customCommand: run-script test

      - task: Npm@1
        displayName: Check coding style
        inputs:
          command: custom
          customCommand: run-script lint
