jobs:
  - job: test
    displayName: Run tests

    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'

      - task: Npm@1
        displayName: npm ci
        inputs:
          command: ci

      - task: Npm@1
        displayName: Check coding style
        inputs:
          command: custom
          customCommand: run lint
