trigger:
  tags:
    exclude:
      - '*'

jobs:
  - job: test
    displayName: Run tests

    pool:
      vmImage: ubuntu-latest

    steps:
      - script: |
          set -e
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y chromium-chromedriver firefox-geckodriver xvfb
        env:
          DEBIAN_FRONTEND: noninteractive
        displayName: Install browsers

      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'

      - task: Npm@1
        displayName: Install dependencies
        inputs:
          command: ci

      - task: Npm@1
        displayName: Build
        inputs:
          command: custom
          customCommand: run-script build

      - script: xvfb-run npm run-script test
        displayName: Browser tests
        env:
          SELENIUM_BROWSER: chrome

      - task: Npm@1
        displayName: Check coding style
        inputs:
          command: custom
          customCommand: run-script lint
